[project]
name = "dora-openarm-data-collection"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "dora-rs-cli==1.0.1",
    "dora-openarm",
    "dora-openarm-cell-lifter",
    "dora-openarm-data-collection-ui",
    "dora-openarm-dataset-recorder",
    "dora-openarm-dummy",
    "dora-openarm-dummy-camera",
    "dora-openarm-dummy-ker",
    "dora-openarm-ker",
    "dora-openarm-kinematics",
    "dora-openarm-mujoco",
    "dora-openarm-quitter",
    "dora-openarm-vr",
    "dora-openarm-webxr",
    "dora-opencv-image-splitter",
    "opencv-video-capture",
    "openarm-driver>=0.5.1",
]

[tool.uv]
package = false

[tool.uv.sources]
dora-openarm = { path = "nodes/dora-openarm", editable = true }
dora-openarm-cell-lifter = { path = "nodes/dora-openarm-cell-lifter", editable = true }
dora-openarm-data-collection-ui = { path = "nodes/dora-openarm-data-collection-ui", editable = true }
dora-openarm-dataset-recorder = { path = "nodes/dora-openarm-dataset-recorder", editable = true }
dora-openarm-dummy = { path = "nodes/dora-openarm-dummy", editable = true }
dora-openarm-dummy-camera = { path = "nodes/dora-openarm-dummy-camera", editable = true }
dora-openarm-dummy-ker = { path = "nodes/dora-openarm-dummy-ker", editable = true }
dora-openarm-ker = { path = "nodes/dora-openarm-ker", editable = true }
dora-openarm-kinematics = { path = "nodes/dora-openarm-kinematics", editable = true }
dora-openarm-mujoco = { path = "nodes/dora-openarm-mujoco", editable = true }
dora-openarm-quitter = { path = "nodes/dora-openarm-quitter", editable = true }
dora-openarm-vr = { path = "nodes/dora-openarm-vr", editable = true }
dora-openarm-webxr = { path = "nodes/dora-openarm-webxr", editable = true }
dora-opencv-image-splitter = { path = "nodes/dora-opencv-image-splitter", editable = true }
